---
variables:

before_script:
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git

debian:10  gcc:c++17:
  image: duneci/base:10
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.gcc.c++17}
  tags: debug

debian:9--gcc:
  image: duneci/base:9
  script: duneci-standard-test
  tags: debug

debian:9--clang:
  image: duneci/base:9
  script: duneci-standard-test
  variables: {HYPERTHREADING: "true", DUNECI_OPTS: /duneci/opts.clang}
  tags: debug

ubuntu:16.04--gcc:
  image: duneci/base:16.04
  script: duneci-standard-test
  tags: debug

ubuntu:16.04--clang:
  image: duneci/base:16.04
  script: duneci-standard-test
  variables: {HYPERTHREADING: "false", DUNECI_OPTS: /duneci/opts.clang}
  tags: debug
